/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 * Created on 2012-01-04, 15:42:19
 */

package gui;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;

import javax.imageio.ImageIO;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import gui.editors.ArrearsWindow;
import gui.editors.SalaryWindow;
import gui.editors.WorkWindow;
import gui.registry.DentistsWorkplaceRegistryWindow;
import gui.registry.DoctorRegistryWindow;
import gui.registry.OfferRegistryWindow;
import gui.registry.TaskRegistryWindow;
import gui.registry.WorkRegistryWindow;
import gui.registry.WorkerRegistryWindow;
import sildent.Config;
import utilities.User;

import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JLabel;

import debug.DebugDisplay;


import java.awt.Canvas;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.awt.event.WindowFocusListener;
import java.awt.event.WindowListener;
import java.io.File;
import java.io.IOException;
import java.awt.Dimension;

/**
 *
 * @author Aleks
 */
public class MainWindow extends javax.swing.JFrame {

    static boolean isAdmin=false;

    /** Creates new form MainWindow */
    public MainWindow() {
    	setResizable(false);
    	getContentPane().setPreferredSize(new Dimension(310, 390));
        initComponents();
        setLocationRelativeTo(null);
        
        
        if(!Config.isConnected)
        	DebugDisplay.popup(this,"Brak ³¹cznoœci z baz¹ danych! SprawdŸ ustawienia.");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        loginMenuItem = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
            	jMenu3.setEnabled(Config.isAdmin);
            }
        });

        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sil-tech");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                checkAdmin(evt);
            }
        });

        jMenu1.setActionCommand("ustawienia");
        jMenu1.setLabel("Ustawienia");

        loginMenuItem.setText("Zaloguj");
        loginMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login(evt);
            }
        });
        jMenu1.add(loginMenuItem);

        jMenuItem10.setText("Ustawienia");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                config(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem12.setText("Kopia bezpieczeñstwa");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backup(evt);
            }
        });
        jMenu1.add(jMenuItem12);
        
        

        jMenuItem11.setText("Zakoñcz");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finish(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuBar1.add(jMenu1);

        jMenu2.setLabel("Kartoteki");

        jMenuItem4.setText("Ewidencja prac");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openWorkRegistry(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem13.setText("Zadania");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openTaskWindow(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuItem1.setText("Pracownicy");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openWorkerRegistry(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Lekarze");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDoctorRegistry(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Gabinety");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDentistsWorkplaceRegistry(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem9.setText("Oferta");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openOfferRegistry(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Zestawienia");

        jMenuItem6.setText("Zaleg³oœci");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openArrearsRegistry(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Wynagrodzenia");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openSalaryRegistry(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Bilans");
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu4.setLabel("Pomoc");

        jMenuItem5.setText("Wersja");
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);
        
        JPanel panel = new JPanel() /*{  
        	public void paintComponent(Graphics g) {  
        		Image img = Toolkit.getDefaultToolkit().getImage(  
        				MainWindow.class.getResource("/img/tooth_logo.jpeg"));  
        		g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);  
        	}  
        }*/;
        
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(20)
        			.addComponent(panel, GroupLayout.PREFERRED_SIZE, 275, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(panel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGap(22))
        );
        
        Image image;
        JLabel picLabel;
		try {
			panel.setSize(232, 240);
			//image = ImageIO.read(new File("resources\\img\\tooth_logo_final.png"));
			//image = ImageIO.read(new File("tooth_logo_final.png"));
			image = ImageIO.read(getClass().getResourceAsStream("/img/tooth_logo_final.png"));
			picLabel = new JLabel(new ImageIcon(image));
			panel.add(picLabel);
			
			//image = ImageIO.read(new File("resources\\img\\button_plus.png"));
			image = ImageIO.read(getClass().getResourceAsStream("/img/button_plus.png"));
			final JLabel addPic = new JLabel(new ImageIcon(image));
			addPic.addMouseListener(new java.awt.event.MouseListener() {

				@Override
				public void mouseClicked(MouseEvent arg0) {
					
					new WorkWindow(true).setVisible(true);
				}

				@Override
				public void mouseEntered(MouseEvent arg0) {
					
					addPic.setIcon(new ImageIcon(getClass().getResource("/img/button_plus_hoover.png")));
				}

				@Override
				public void mouseExited(MouseEvent arg0) {
					
					addPic.setIcon(new ImageIcon(getClass().getResource("/img/button_plus.png")));
				}

				@Override
				public void mousePressed(MouseEvent arg0) {
					// TODO Auto-generated method stub
					
				}

				@Override
				public void mouseReleased(MouseEvent arg0) {
					// TODO Auto-generated method stub
					
				}
	        });
			
			
			panel.add(addPic);
			
	        panel.repaint();
		} catch (IOException e) {
			System.out.println();
			e.printStackTrace();
		}
        
        
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void backup(ActionEvent evt) {
		
    	try {
			Runtime.getRuntime().exec("cmd /c start scripts\\Backup.bat");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}

	private void openWorkRegistry(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openWorkRegistry

        new WorkRegistryWindow().setVisible(true);
    }//GEN-LAST:event_openWorkRegistry

    private void openWorkerRegistry(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openWorkerRegistry
        new WorkerRegistryWindow().setVisible(true);
    }//GEN-LAST:event_openWorkerRegistry

    private void openDoctorRegistry(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDoctorRegistry
        new DoctorRegistryWindow().setVisible(true);
    }//GEN-LAST:event_openDoctorRegistry

    private void openDentistsWorkplaceRegistry(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDentistsWorkplaceRegistry
        new DentistsWorkplaceRegistryWindow().setVisible(true);
    }//GEN-LAST:event_openDentistsWorkplaceRegistry

    private void openOfferRegistry(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openOfferRegistry
        new OfferRegistryWindow().setVisible(true);
    }//GEN-LAST:event_openOfferRegistry

    private void openArrearsRegistry(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openArrearsRegistry
        new ArrearsWindow().setVisible(true);
    }//GEN-LAST:event_openArrearsRegistry

    private void openSalaryRegistry(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openSalaryRegistry
        new SalaryWindow().setVisible(true);
    }//GEN-LAST:event_openSalaryRegistry

    private void login(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login
        if( Config.isAdmin )
            Config.isAdmin = false;
        else
            new LoginWindow().setVisible(true);
    }//GEN-LAST:event_login

    private void finish(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finish
        System.exit(0);
    }//GEN-LAST:event_finish

    private void checkAdmin(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_checkAdmin
        if( Config.isAdmin ){
            this.setTitle("Sil-tech - zalogowano jako administrator");
            loginMenuItem.setText("Wyloguj");
        } else {
            this.setTitle("Sil-tech");
            loginMenuItem.setText("Zaloguj");
        }
    }//GEN-LAST:event_checkAdmin

    private void config(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_config
        new ConfigWindow().setVisible(true);
    }//GEN-LAST:event_config

    private void openTaskWindow(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openTaskWindow
        new TaskRegistryWindow().setVisible(true);
    }//GEN-LAST:event_openTaskWindow

    
    
	/**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
    	
    	
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem loginMenuItem;
}
